---
title: "Data Mining - Group 6 - Assignment 1"
author: "Suman Ravichandran"
date: "10/4/2020"
output: pdf_document
---


```{r setup, include=FALSE}
library(ggplot2)
library(GGally)
library(cowplot)
library(dplyr)
library(reshape2)
library(fitdistrplus)
library(scatterplot3d)
library(plotrix)
library(RColorBrewer)
knitr::opts_chunk$set(echo = TRUE)

```


#Problem 1 a 
```{r}
# Dataset import 
forest_fires <- data.frame(read.csv("forestfires.csv"),
                          stringsAsFactors = FALSE)

# Change the month column into factors and arrange them from Jan to Dec
forest_fires$month <- factor(forest_fires$month,
                            levels = c(
                              "jan", "feb", "mar",
                              "apr", "may", "jun",
                              "jul", "aug", "sep",
                              "oct", "nov", "dec"))

# Creating 4 scatter plots
plot_1 <- ggplot(forest_fires, aes(temp, area)) +
  geom_point(color = "#d63447", alpha = 0.5) +
  ggtitle("Temp vs Area") +
  theme_classic()
plot_2 <- ggplot(forest_fires, aes(month, area, color = month)) +
  geom_point() +
  scale_color_brewer(palette = "Set3") +
  theme_classic() +
  theme(legend.position = "none") +
  ggtitle("Month vs Area")
plot_3 <- ggplot(forest_fires, aes(DC, area)) +
  geom_point(color = "#d63447", alpha = 0.5) +
  ggtitle("DC vs Area") +
  theme_classic()
plot_4 <- ggplot(forest_fires, aes(RH, area)) +
  geom_point(color = "#d63447", alpha = 0.5) +
  ggtitle("RH vs Area") +
  theme_classic()

# Arranging the plots - Plot 1  to Plot 4 into a 2x2 grid
plot_grid(plot_1, plot_2, plot_3, plot_4)

rm(list = c("plot_1", "plot_2", "plot_3", "plot_4"))

```


#Problem 1 b
```{r}
# Creating the Wind-Historgram
wind_hist <- ggplot(forest_fires, aes(wind)) +
  geom_histogram(bins = 10, fill = "#08d9d6", color = "black") +
  theme_classic() +
  ggtitle("Histogram of Wind Speed") +
  labs(x = "Wind Speed (km/hour)")

# Ploting the histogram
plot(wind_hist)

rm(wind_hist)
```

#Problem 1 c
``` {r}
# Calculate the Quantiles values of Wind Speed
ff_quantiles <- quantile(forest_fires$wind)

# Printing the quantile values
cat("Min Wind Speed is :", ff_quantiles[[1]], "\n")
cat("First (1st) Quantile of the Wind Speed is :", ff_quantiles[[2]], "\n")
cat("Average Wind Speed is :", mean(forest_fires$wind), "\n")
cat("Median Wind Speed is :", ff_quantiles[[3]], "\n")
cat("Third (3rd) Quartile of the Wind Speed is :", ff_quantiles[[4]], "\n")
cat("Max Wind Speed is :", ff_quantiles[[5]], "\n")

rm(ff_quantiles)

```

#Problem 1 d
```{r}
# Creating the Histogram and Density Plot
wind_hist_density <- ggplot(forest_fires, aes(x = wind, y = ..density..)) +
  geom_histogram(bins = 10, colour = "black", fill = "#0999d7") +
  geom_density(aes(y = ..density..), color = "black") +
  ylab("Density") +
  xlab("Wind Speed (km/hour)") +
  ggtitle("\t \t Histogram of Wind Speed") +
  theme_bw()

plot(wind_hist_density)

rm(wind_hist_density)

```

#Problem 1 e
```{r}
# Creating month wise density plot
month_density <- ggplot(forest_fires, aes(
  x = wind,
  y = ..density..,
  fill = month
)) +
  geom_density(alpha = 0.8) +
  scale_fill_brewer(palette = "Set3") +
  theme_classic() +
  ggtitle("Wind Speed Density Plots for each month") +
  labs(x = "Wind Speed (km/hour)", y = "Density", fill = "Month") +
  scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA))

plot(month_density)

rm(month_density)
```

#Problem 1 f
```{r}
# Plotting the ScatterMatrix
ggpairs(forest_fires,
        title = "Scatterplot Matrix",
        columns = c("temp", "RH", "DC", "DMC"))


# 1. Temp and RH are negatively correlated with corr. coeff of -0.527
# 2. Temp and DC are positively correlated with corr. coeff of 0.496
# 3. Temp and DC are positively correlated with corr. coeff of 0.47
# 4. RH has no correlation with DC and DMS.
# 5. DC and DMC are very strongly correlated with a corr. coeff of 0.682
```


#Problem 1 g
```{r}

# Creatng a temporary dataframe and reshape it
suppressMessages({
  forest_fire_reshape <- melt(forest_fires)
})

# Boxplots for Wind, ISI, and DC
ggplot(forest_fire_reshape %>% filter(variable == "wind"), aes(x = variable, y = value, fill = variable)) +
  geom_boxplot() +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank()
  ) +
  ggtitle("Wind Speed Box Plot") +
  labs(x = "Wind Speed", y = "Value")

ggplot(forest_fire_reshape %>% filter(variable == "ISI"), aes(x = variable, y = value, fill = variable)) +
  geom_boxplot() +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank()
  ) +
  ggtitle("ISI Box Plot") +
  labs(x = "ISI", y = "Value")

ggplot(forest_fire_reshape %>% filter(variable == "DC"), aes(x = variable, y = value, fill = variable)) +
  geom_boxplot() +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank()
  ) +
  ggtitle("DC Box Plot") +
  labs(x = "DC", y = "Value")


rm(forest_fire_reshape)

# Inferences from the scatter plot matrix
# 1. ISI has a few outliers which can be seen beyong the boxplots
# 2.  DC has only 2 outliers on the lower side but it is only 2 values
```


#Problem 1 h
```{r}

# Plot normal histogram
ggplot(forest_fires, aes(DMC)) +
  geom_histogram(binwidth = 50, color = "black", fill = "#88d9d6") +
  theme_classic() +
  ggtitle("DMC Histogram")

# Plot log scale histogram
ggplot(forest_fires, aes(log10(DMC))) +
  geom_histogram(bins = 8, color = "black", fill = "#88d9d6") +
  theme_classic() +
  ggtitle("LOG DMC Histogram") +
  scale_x_log10()

# Inferences from the scatter plot matrix
#  1. DMC normal Histogram: We can infer that it follows a normal distribution consisting of values of the range 100-150. It is a little skewed to the left.

# 2. DMC lognormal Histogram: We can infer that the values are in the range of 150-300 and it is logical that the  histogram shows the values at 2 (since the value of log10(X>100) lies in range 1-2).

```

#Problem 2a
```{r}

# Import dataset and filter negative values
twitter_data <- data.frame(read.csv("M01_quasi_twitter.csv"))
twitter_friends_count <- filter(twitter_data, friends_count > 0)

# Plotting log scale histogram because of the skewness 
ggplot(twitter_friends_count, aes(log10(friends_count))) +
  geom_histogram(color = "red", fill = "#88d9d6") +
  scale_x_log10()

# Fitting a distribution on the dataset
descdist(twitter_friends_count$friends_count)

fit_log_norm <- fitdist(twitter_friends_count$friends_count, "lnorm")

# Goodness of fit plot
plot(fit_log_norm)

rm(twitter_friends_count, fit_log_norm)

# Inferences from the plots
# 1. friends_count variable follows a lognormal distribution

```

#Problem 2b
```{r}
# Calculating the Quantiles values
twitter_quantiles <- quantile(twitter_data$friends_count)

# Print
cat("Min friends_count is :", twitter_quantiles[[1]], "\n")
cat("First (1st) Quantile of friends_count is :", twitter_quantiles[[2]], "\n")
cat("Average friends_count is :", mean(twitter_data$friends_count), "\n")
cat("Median friends_count is :", twitter_quantiles[[3]], "\n")
cat("Third (3rd) Quartile of friends_count is :", twitter_quantiles[[4]], "\n")
cat("Max friends_count is :", twitter_quantiles[[5]], "\n")

rm(twitter_quantiles)


```

#Problem 2c
```{r}
# We can infer that the friends_count variable is a highly skewed. It also has values which are negative which is not realistically possible. A few users who have friends count in thousands make the data skewed as most of the users have friends in the range of hundreds. On the whole, it is not a quality data.

```

#Problem 2d
```{r}
# Create and Plot the 3D Scatter Plot
scatterplot3d(
  x = twitter_data$created_at_year,
  y = twitter_data$education,
  z = twitter_data$age,
  main = "3D scatter plot",
  xlab = "created_at_year",
  ylab = "education",
  zlab = "age",
  highlight.3d = TRUE
)

```

#Problem 2e
```{r}

# Create a temporary dataframe for the twitter_data
twitter_temp <- data.frame(
  "country" = c("UK", "Canada", "India", "Australia", "US"),
  "num_accounts" = c(650, 1000, 900, 300, 14900)
)

# Mutate the dataframe to create a percentages columns
twitter_temp <- twitter_temp %>%
  group_by(country) %>%
  arrange(desc(country)) %>%
  mutate(prop = 100 * round(num_accounts / sum(twitter_temp$num_accounts), 3)) %>%
  mutate(percentage_labels = paste0(prop, "%"))
# Define the grid, 1 row x 2 columns
par(mfcol = c(1, 2), mar = c(5, 5, 5, 5))

# 3D Pie chart
pie3D(twitter_temp$prop,
      radius = 0.9,
      labels = twitter_temp$country,
      main = "Country 3D Pie Chart"
)
# Regular Pie Chart
pie(twitter_temp$prop,
    labels = paste0(twitter_temp$country, " ", twitter_temp$percentage_labels),
    col = brewer.pal(5, "Dark2"),
    cex = 1
)

rm(twitter_temp)

```

#Problem 2f
```{r}

ggplot(twitter_data, aes(x = created_at_year)) +
  geom_density() +
  scale_x_continuous(
    breaks = c(
      2006, 2007, 2008,
      2009, 2010, 2011,
      2012, 2013, 2014,
      2015, 2016, 2017
    ),
    labels = c(
      "2006", "2007", "2008",
      "2009", "2010", "2011",
      "2012", "2013", "2014",
      "2015", "2016", "2017"
    )
  )

rm(twitter_data)

# From the booming in the year 2006, the number of accounts peaked in the year 2009 and has been fluctuating every year since. 

```
#Problem 3a
```{r}
# Import the raw_data.csv file
raw_data <- data.frame(read.csv("raw_data.csv"), stringsAsFactors = FALSE)

# Standardize the data frame using the scale function
scale_data <- as.data.frame(scale(raw_data))
```

#Problem 3b
```{r}
raw_data_melt <- melt(raw_data)

# Create box plots
ggplot(raw_data_melt, aes(variable, value, fill = "value")) +
  geom_boxplot() +
  theme_classic() +
  ggtitle("Box Plot for raw_data") +
  labs(x = "") +
  theme(legend.position = "none")

rm(raw_data_melt)

```

#Problem 3c
```{r}
scale_data_melt <- melt(scale_data)

# Create box plots
ggplot(scale_data_melt, aes(variable, value, fill = "value")) +
  geom_boxplot() +
  theme_classic() +
  ggtitle("Box Plot for Ndata") +
  labs(x = "") +
  theme(legend.position = "none")

rm(scale_data_melt)

```
#Problem 3d
```{r}

# From the two previous plots we can infer that the standardization step transforms all of the columns to a std. normal distribution with a mean of 0 and a standard deviation of 1. This also scales the data. 
```


#Problem 3e
```{r}
ggplot(raw_data, aes(A, B)) +
  geom_point() +
  ggtitle("Scatterplot of A and B")

# From the plot we can infer that A and B are independent as there is no correlation. 
```